### PR TITLE
Fix OS singleton being incorrectly highlighted as a constant

### PR DESCRIPTION
**Pull request by DaelonSuzuka**
Code_55p7kAtleh

### CODE REVIEW

**Comment by Calinou** [comment]
OS is not a primitive type, so it shouldn't be highlighted this way. The issue is likely elsewhere.

**Comment by DaelonSuzuka** [comment]
All the other built-in singletons are PascalCase so they're green like classes.

image

**Comment by Calinou** [comment]
My guess is that the `const` highlight is kicking in as the identifier's name is all-uppercase.

**Comment by DaelonSuzuka** [comment]
Yeah, that's exactly what's happening. OS doesn't trigger the same rule as the other singletons because it doesn't have any lower case letters. This change is just bringing OS in line with the other singletons.

**Review by Calinou — APPROVED** [review]
Thanks!

**Pull request merged**
