### PR TITLE
Set up continuous integration using GitHub Actions

### PR DESCRIPTION
**Pull request by Calinou**
The extension will be built and uploaded to artifacts so it can be tested easily by users.

This also fixes warnings reported by TSLint.

### CODE REVIEW

**Comment by Calinou** [comment]
@Geequlim Why not push it? It ensures everyone's using the same version of all the dependencies.

**Comment by Geequlim** [comment]
I think the dependencies version are defined in package.json

**Comment by Calinou** [comment]
> I think the dependencies version are defined in package.json

Yes, but only partially. package.json will only constrain the versions for direct dependencies, not indirect dependencies. Also, [it allows installing newer semver-compatible versions](https://github.com/godotengine/godot-vscode-plugin/blob/master/package.json#L275-L294) due to the use of the caret symbol (`^`) in version ranges.

**Comment by Razoric480** [comment]
Having just run into an issue where the code is different between 2 of my machines because my `package-lock.json` was different, I can assure that having a package-lock.json pushed to the repo to be a good thing.

**Pull request merged**
