### PR TITLE
Fix typo "guii" -> "gui" and "decleration" -> "declaration"

### PR DESCRIPTION
**Pull request by LightningAA**

### CODE REVIEW

**Comment by Calinou** [comment]
I think the `guii` *might* be intentional, since you don't want it to appear every time you enter "gui". I'm not 100% sure though.

**Comment by Razoric480** [comment]
I think Calinou's got it, yeah. Looks like it was intentional to me to allow the use of a variable called gui (which would be fairly common) without triggering VSCode's snippets.

The other looks like a typo to me.

**Comment by Calinou** [comment]
> The other looks like a typo to me.

The "declaration" typo has been fixed in https://github.com/godotengine/godot-vscode-plugin/pull/262 already :slightly_smiling_face:

**Comment by LightningAA** [comment]
Alright, sound good

**Pull request closed without merging**
