### PR TITLE
Debugger Fixes for Godot 4.0

### PR DESCRIPTION
**Pull request by QuinsZouls**
I been working on godot 4 support, also thanks to @DaelonSuzuka, @RedMser, @ZachIsAGardner  for their work (I included some of their changes), here's  my changes and implementations:
## Debugger
- [bugfix: fixes class_name.replace exception](https://github.com/godotengine/godot-vscode-plugin/commit/65e24d712a581714fd8882acce2151732e729d13)
- [bugfix: fixes godot type for run and debug option](https://github.com/godotengine/godot-vscode-plugin/commit/b851fa067ea8e056e1247d512b371457b437bae0)
- [remove: delete unused Mediator package](https://github.com/godotengine/godot-vscode-plugin/commit/687c7528b8d21ef92962c2acab2b08c54e9a5934)
- [feature: add command trigger functionality for godot4](https://github.com/godotengine/godot-vscode-plugin/commit/ec94423ad0e28996439067ca29045dfc7da48955)
- [refactor: change all commands godot-tool to godot4-tool](https://github.com/godotengine/godot-vscode-plugin/commit/e6defad7b6d75c8018874555606169aa9e67c778)
- [update: change godot template](https://github.com/godotengine/godot-vscode-plugin/commit/34ec3781155197261bfea7c06912295cbb87965d)
- [feature: implement ability to inspect in Debug Console](https://github.com/godotengine/godot-vscode-plugin/commit/ad2becf6759e65fda5548754031b3a0695fbf8a3) ref: #387 
- [fix: fixes type error](https://github.com/godotengine/godot-vscode-plugin/commit/78b67699e64cb473da0176a21041d28b304715c0)

- [feature: add get_godot_version function](https://github.com/godotengine/godot-vscode-plugin/commit/26b55ed8b3427b0e65cf273fa232ef2d183f7a23)
- [feature: implements godot version detection](https://github.com/godotengine/godot-vscode-plugin/pull/456/commits/ea28867af1e334e03b9b0fbe66e4a8585751c527)
## TODO
- [x] Detect godot version to setup an specific version (I already have a function to detect the godot version but im not sure how implements to setup an specific version of debugger)

### CODE REVIEW

**Comment by DaelonSuzuka** [comment]
Hi @QuinsZouls,

Thank you for you interest in improving this extension! I appreciate that you took the time to put this together and submit it. 

Unfortunately, there are a number of problems with this PR that mean it can't be accepted.

## **Please do not combine multiple PRs together!**
There are a lot of reasons not to do this, but one of the biggest is that you end up with a giant PR that touches way too many things, and that makes it much harder for other people to review it effectively.

It's important to understand all of the changes that are being made to a project, and that's more difficult to do if you're combining a bunch of other patches. As an example, PR #452 is highly experimental and DOES NOT WORK. It's marked as a draft because it's currently in-progress and very, very broken. The fact that it's included makes me seriously question if anything in this PR was tested.

The changes to `tsconfig` and the package updates are interesting, but I can't properly evaluate that stuff with how much other content is here. If you resubmitted those changes in a new PR by themselves, it's likely we'd be able to accept them.

**Comment by QuinsZouls** [comment]
Well, I'd to make single PR for each patch, thanks for you feedback, also I show you how my changes work (I didn't just merge all code, during the merge commit I made some fixes):

https://user-images.githubusercontent.com/40646096/222931901-a3ad6b59-4052-411c-a7fa-b3b668e2a1bc.mp4

**Comment by QuinsZouls** [comment]
I split all icons changes to a new PR
This PR now focuses on debugger compatibility for godot 4.

**Comment by QuinsZouls** [comment]
BTW My changes made it work your PR #456

**Comment by atirut-w** [comment]
Well that's sad

**Pull request closed without merging**
