### PR TITLE
feat(snippets): add match statement

### PR DESCRIPTION
**Pull request by Mawdac**
Adding the same contribution I did here: https://github.com/rafamadriz/friendly-snippets/pull/300

### CODE REVIEW

**Comment by Mawdac** [comment]
@Calinou No worries, I was just going through my open PR's and realized this snippet is both poorly written and also wrong lol. I need to update it here and fix the already merged one in friendly-snippets.

**Comment by Mawdac** [comment]
Ok, this is fixed so that it reflects the [actual match syntax](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#match) This should be ready to merge from my perspective @Calinou

**Comment by Mawdac** [comment]
@Calinou feel free to check/merge this when it's convenient, I think it's ready now.

**Review by Calinou — APPROVED** [review]

**Comment by Calinou** [comment]
Thanks! Congratulations for your first merged pull request :tada:

**Pull request merged**
