### PR TITLE
Capitalize the drive letter in windows absolute paths

### PR DESCRIPTION
**Pull request by DaelonSuzuka**
RE: #726 

@KoBeWi please grab the CI build and let me know if this solves your problem

### CODE REVIEW

**Comment by KoBeWi** [comment]
It solves the problem, but looks like a hack. Why is `projectDir` like that?

**Comment by DaelonSuzuka** [comment]
I don't understand the question. Why is `projectDir` like what?

**Comment by DaelonSuzuka** [comment]
`path.dirname()` is from the Node standard library, and apparently it returns Windows paths with a lower case drive letter. What is it you're expecting me to do about that?

**Comment by KoBeWi** [comment]
Ah so it's just some Node weirdness.

> What is it you're expecting me to do about that except fix the return value?

I was mostly curious, because it looks like bandaid fix. But if the problem is standard library then it's the only way I guess.

**Comment by DaelonSuzuka** [comment]
> Ah so it's just some Node weirdness.

Pretty much. It preserves the case in the rest of the path, for some reason: ie it doesn't lower the path part of `p:/SkyknightsOnline` on my machine, just the drive letter.

**Pull request merged**
