### PR TITLE
Add check for PowerShell 7 executable name

### LINKED ISSUE #201: Godot start command does not work with Powershell 7.x
The GodotTools command for starting the Godot editor does not work with Powershell 7.x:
Screenshot of invalid command

To make the command valid, `& ` must be prepended.
Screenshot of corrected command

### PR DESCRIPTION
**Pull request by a-type**
Fixes #201

### CODE REVIEW

**Comment by taylorjoshuaw** [comment]
I'd probably name that constant POWERSHELL_CORE rather than POWERSHELL_7

**Comment by taylorjoshuaw** [comment]
I just thought of something -- Powershell Core isn't tied to Windows like the old Powershell was. It might be a good idea to move your change out of the win32 platform check and not expect a ".exe" extension at the end . Sorry I didn't catch that before.

**Comment by a-type** [comment]
@taylorjoshuaw good point! I can do that.

**Comment by Calinou** [comment]
Is this mergeable as-is? Maybe we can continue improving this later.

**Comment by taylorjoshuaw** [comment]
@Calinou Good to see you around here (I was about to ask if you needed some help merging PR's). It should be good to merge. I think the amount of people using this plugin and Powershell Core as their integrated shell on non-Windows platforms is probably pretty limited.

**Review by Calinou — APPROVED** [review]
Thanks!

**Pull request merged**
